### ISSUE TITLE
Request paper

### ISSUE THREAD

**Issue by wangwenying1** [Wayne-on-the-road/B-CITD#1]
Could you please share your paper? As for the data processing part, I hope you can have a look at the specific part of the paper.Thank you

**Comment by Wayne-on-the-road** [comment]
Hi, 

Sorry, I forgot to put the link to my paper on Git Hub. The title of the paper is "Graph Intelligence Enhanced Bi-Channel Insider Threat Detection". You can either search from Google Scholar or open this link from Springer: https://link.springer.com/chapter/10.1007/978-3-031-23020-2_5



Wei Hong
Victoria University, Melbourne
 
From: wangwenying1
Date: 2024-05-15 23:00
To: Wayne-on-the-road/B-CITD
CC: Subscribed
Subject: [Wayne-on-the-road/B-CITD] Request paper (Issue #1)
Could you please share your paper? As for the data processing part, I hope you can have a look at the specific part of the paper.Thank you

**Comment by wangwenying1** [comment]
> Hi, Sorry, I forgot to put the link to my paper on Git Hub. The title of the paper is "Graph Intelligence Enhanced Bi-Channel Insider Threat Detection". You can either search from Google Scholar or open this link from Springer: https://link.springer.com/chapter/10.1007/978-3-031-23020-2_5 Wei Hong Victoria University, Melbourne From: wangwenying1 Date: 2024-05-15 23:00 To: Wayne-on-the-road/B-CITD CC: Subscribed Subject: [Wayne-on-the-road/B-CITD] Request paper (Issue #1) Could you please share your paper? As for the data processing part, I hope you can have a look at the specific part of the paper.Thank you — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by wangwenying1** [comment]
Thank you for your reply.
